### ISSUE TITLE
Build 2016 India  Advocacy Plan 

### ISSUE THREAD

**Issue by anivar** [MozINadvocacy/plan#1]
Meta Bug for building 2016 India Advocacy Plan 
## Key Components:

Leadership
Intervention
Teaching
## Roles:

Owner: Anivar
Involved: @asdofindia

**Comment by asdofindia** [comment]
We probably should add in-between steps and deadlines to this or it won't get done. I've wrote a small bit down in [this pad](https://public.etherpad-mozilla.org/p/India_Advocacy_Plan_2016).

**Comment by asdofindia** [comment]
Closing this as the task force has been disintegrated.
