### ISSUE TITLE
Get the task force started on blogging

### ISSUE THREAD

**Issue by asdofindia** [MozINadvocacy/plan#2]
- [x] Form a consensus on [how we should blog](https://discourse.mozilla-advocacy.org/t/how-should-we-blog/321) by Dec 1
- [x] Document the process for a new post to reach the blog. By Dec 5

**Comment by subu-rg** [comment]
Let's vote upon a forum (or blog) moderator who approves all the posts.

We'll look for a heads up from the legal team if it involves sensitive issues or serious concerns. 

And further, I'd love if we could get started on the Task Force roadmap for 2016. 

Finally, regarding the topics, I'd prefer a wider accomodation (not limited to the topics we presently have). Anything regarding the open web can be taken up I suppose (lest it makes sense)

**Comment by asdofindia** [comment]
Till there can be a better place to keep it, the policy that's preferred is documented at the [3rd comment here](https://discourse.mozilla-advocacy.org/t/how-should-we-blog/321/3)
