### ISSUE TITLE
January 2016 Privacy Campaign

### ISSUE THREAD

**Issue by diwanshi** [MozINadvocacy/plan#4]
## Introduction:

We are planning a privacy campaign in January for Data Privacy Day (28th January) which would run throughout the month. The goal is not only to aware people about their online privacy but to teach them how to teach privacy in their own regions.
## Plan:
- Host online as well as offline privacy focused teaching events.
- Share privacy tips online via social media every day in the month of january. 
- Answer privacy related questions on twitter like last year Mark Surman did using #PrivacyChat.
- Share teaching kits online so that others can also educate people on privacy using those teaching kits.
- Conduct 1 hour to 3 hour privacy sessions/events in schools/colleges/other places like residential society's depending upon the knowledge of audience.
## Tasks:
- A draft for all these things with agenda.
- Pick up roles.
- 31 Privacy tips.
- Select topics for 6 Teaching kits.
- Reps event pages for offline events.
- Contact other communities in India and ask them if they would be interested in running the offline events.
- more to come will keep this updated
- Collect swags from stacy in workweek.
- Decide on ways to distribute swag.
## Tasks Done:
- 31 privacy tips thanks @Siddhartha Rao.
- A template of teaching kit.
- Mayur will be collecting swag from stacy.
## Roles:

Following are the names of people who agreed to work on the above tasks:
- Sidhhartha Rao - Privacy Tips
- Diwanshi, Ankit Mehta, Siddhartha Rao working on teaching kits 2 each.
- Ankit Gadgil and Mayur Patil will be helping with outreach of the events.
- Vishal Chavan is working on wiki.
## Note:
- If someone is interested to help please comment and tell us how you want to help.
- If you have ideas on what more we can do, comment them too.

**Comment by diwanshi** [comment]
This is just half of wat needs to be included will update it more once i have a draft pepared.

**Comment by ashmis** [comment]
I would like to with the digital marketing of this campaign :)

**Comment by diwanshi** [comment]
# Updates On the Plan:

## Important Note:

**Please don't share the teaching kits and tips with anyone yet as we want them to go online on 1st of January. The task force members can review them and provide feedback though.**

## Wiki:
- https://wiki.mozilla.org/India/task_force/Policy_and_Advocacy/January_Privacy_Month_Campaign

## Blog
- http://blog.mozillaindia.org/1569

## Official Twitter Hashtags:
- #PrivacyMonth 
- #advocate4privacy

## Official Twitter Handle:
- I don't have still update on the official handle. Stacy mentioned some Mozilla Official twitter handle.
- But as we already have Mozilla India channel we will also be tweeting from that handle.

## 31 Tips:
- Below is the link to 31 Teaching Tips which was initially given by Stacy for privacy campaign which each day we will be sharing. Link: https://docs.google.com/spreadsheets/d/1toEov3dUaRfm6UFJGUOc9hJGNFlqXkPtoaembX-iSIo/edit?usp=sharing 
- We have created a copy of these tips and working on the content of the tips. (Siddhartha Rao and Ankit Mehta have taken lead for that). But still we all will review the content once.

## Completed Teaching Kits:

We are creating the kits based on the above tips. However, we will not be creating 31 kits for each tip. We are taking out the important ones and creating kits on those.
- Information Footprint (Have you measured your footprints? They are larger than you think) : https://diwanshi.makes.org/thimble/MjAzODM2NjcyMA==/information-footprint
- Lightbeam (Look Who's Tracking): https://d157rqmxrxj6ey.cloudfront.net/diwanshi/21765/
- Passwords (What's wrong with your passwords) : https://stacy.makes.org/thimble/MjAxMjIxNzYwMA==/whats-wrong-with-your-password

## In-Progress Teaching Kits:

I am currently working on making kits on : 
- Cookies
- Protect your Data (Will include Do Not Track, Forget Button, about:permissions)
- Net Neutrality (I already have Siddhartha's Slide just need to make it short and simple and finally convert it into a kit) Here is the slide link: http://www.slideshare.net/mrperfect17/net-neutrality-complete
- SQL Injection: Siddhartha has shared content with me for this but as its too technical he is working on simplifying it.
- Tracking Protection (The firefox 42 feature)
- For now these are the once we will be creating if needed be we will create more based on the topics.

## Swags:
- In Mozlando, Stacy gave out some privacy lab stickers to Mayur Patil. He will be sharing them soon. 
- Stacy has shipped swag (stickers mostly) to Siddhartha Rao's address. He is in Pune. 
- We are still thinking how will we distribute them for other cities.

## Online/Offline Events:
- Recently, we had a Mozcafe Pune where we shared updates on Privacy Campaign and we got a good response from attendees.
- We have been talking to people who will be able to organize offline events in their school or colleges.
- Also we have been contacting other regional community members to help us in on/offline events.
- Updates from Pune: The community members have already contacted a school, few colleges and even their residential societies  to organize privacy focused events. 

## Social Media:
- I have already mentioned about the tags and handle earlier.
- Though we need posters , There is one which was shared on fb group (If someone has link please paste it in comments). I think Akshay Chitwar from Pune and Jafar can help us in that. 
- I will email Stacy about the official handle to share tips and resources. and update here as soon as I get reply from her.

## Localization:
- In the Mozcafe Pune, Chandrakant ji (Marathi localization lead) suggested to have the tips in Hindi or Marathi so we shared them with him. He is also working on localizing the tips.
- If anyone want to localize them n their regional language please let us know

**Comment by diwanshi** [comment]
## Updates on Social Media:

The Tips will be shared from Mozilla India Channels. Official Mozilla Advocacy team will retweet our tweets as they said this initiative is taken by Indian community so the tweets should be shared by Mozilla India channels.

**Comment by pmjcreations** [comment]
Thanks for the heads up @diwanshi. I just wanted to remind you that, I have to get _enough_ time to review the contents which will be posted using MozIN Social channels. There would be an iteration needed for any content, whether it's a copy or media asset. Please make sure that, you are providing me enough time to do the review, iteration and other process.

**Comment by ankitgadgil** [comment]
Some new updates from the campaign.

## Wiki:
- https://wiki.mozilla.org/India/task_force/Policy_and_Advocacy/January_Privacy_Month_Campaign

## Blog
- http://blog.mozillaindia.org/1569

## Social
- Follow https://twitter.com/hashtag/privacymonth for updates and latest tweets.
- Follow tweets from https://twitter.com/MozillaIN for tip of the day posts. 
- Follow https://twitter.com/mozinadvocacy for more posts related to tip of the day.

## Offline events:

We have some events lined up this January globally. 
Reps portal is the only place we can track these events : https://reps.mozilla.org/events/#/period/future/search/privacy/

## Graphic resources.

These have been updated. Supporter can change there Twitter, Facebook cover pictures.
https://drive.google.com/drive/folders/0BwPpoF4oy3uUcnFKRjZQN3k4M3M

**Comment by pmjcreations** [comment]
@ankitgadgil, 

http://bit.ly/1R6K8Ij returning a 404. Please, check that.

**Comment by ankitgadgil** [comment]
@pmjcreations fixed, see above.
Thanks for the report.
