### ISSUE TITLE
Documenting Mozilla community efforts on Savetheinternet 3 

### ISSUE THREAD

**Issue by anivar** [MozINadvocacy/plan#5]
bug to collect the efforts of mozilla india policy and advocay community during trai consultation on differential pricing

**Comment by dhaneshsabane** [comment]
Compiled a list of Firefox Clubs' and their Leads' mail IDs and forwarded a mail asking them to SaveTheInternet.

**Context of mail:**

The Telecom regulatory Authority of India(TRAI) has issued a Consultation Paper on Differential Pricing for Data Services on December 9, 2015 and invited public comments to be sent by December 30, 2015. The paper discusses issues related to Net neutrality , a core principle of Internet. Many Indian citizens including Mozillians are actively responding to TRAI's consultation paper via savetheinternet.in and advocating the principles of net neutrality and open Internet.  Facebook and some telecom service providers are now in a misinformation campaign to get policy acceptance for their Net neutrality violating projects and disrupt the Internet’s level playing.

The Internet needs to be 'open' and 'neutral' and we have to stand up to defend the Web. Mozillians are well known as the protectors of the open Web. If we do nothing, there would be no one either. TRAI needs to know that we need net neutrality, once again. Head over to http://www.savetheinternet.in/ and mail to TRAI  for Net Neutrality. There will be a pre filled template . Copy To and CC addresses , read the mail carefully and send if you agree with it.

It will be good if you can mobilize your friends and local community for taking this action.

Learn more about Net Neutrality here: https://www.youtube.com/watch?v=AAQWsTFF0BM

Also, you can read the blog posts on http://www.savetheinternet.in/ to know more about Net Neutrality, Free Basics and the #SaveTheInternet mission.

Here's what Mozilla has to say on Net Neutrality :
1. https://blog.mozilla.org/netpolicy/2015/05/05/mozilla-view-on-zero-rating/
2. http://blog.mozillaindia.org/1418

Friends, we all are the stakeholders of this campaign. Please activate yourself. Be a great influence to save the Internet.

The last date to send a mail to TRAI is  is 30th Dec 2015.

Spread the word among your community and help save the Internet.

**==End of mail==**

**Note:** All the recipients were informed about the extension of the deadline to register their vote.

**Comment by anivar** [comment]
@Dhanesh95 Can you compile and send a new update mail  with submission extension details, Major updates (rejection of Facebook submissions , Industry bodies in support of netneutrality and Telecos against open internet )
suggested actions (Sending email, eg. netneutrality teachins etc  )

**Comment by asdofindia** [comment]
Closing this as the task force has been disintegrated.
