### ISSUE TITLE
A tool to track community level initiatives & campaigns

### ISSUE THREAD

**Issue by abhi12ravi** [MozINadvocacy/plan#8]
Advocacy at the community level comes up with a lot of campaigns & to run an effective campaign we need to know who is doing what and where. In a geographically distributed setup like Mozilla India it becomes all the more important. 

Initial set of requirements:
- A dashboard-like setup to have a one-place info
- Real time (near real time) data display about the campaign status
- ~~Social media impressions tracker~~

Feel free to add ideas!

**Comment by hackkery** [comment]
This is what I think we really require right now!
- A proper structure to track offline events.
- Using that structure we should create a tool for tracking offline events.
- Three make sure all events/campaigns which go offline are tracked using this tool.

Our community must be unbiased to both online as well as offline contributors.Hence I'd suggest this would work best for us.

**Comment by pmjcreations** [comment]
We do have a tracking and managing tool for all our Social efforts. So no need to invest in it.

**Comment by hackkery** [comment]
If we do,We should start to use it to track in all Campaigns/Events.

**Comment by abhi12ravi** [comment]
Are the requirements finalized?
@anivar @ankitgadgil @asdofindia @diwanshi @pmjcreations @roopaksuresh 

Please go through this request and I'd like to know if any other features are required for our _campaign-tracker_ to be built.

**Comment by pmjcreations** [comment]
We need to have answers to a lot of questions. Below are a few example questions.
1. How to collect the data?
2. Who can add them to the dashboard?
3. How we will make it more transparent and provide inclusion?
4. Do we have any measure of success/impact of any offline events?

So my suggestion is let build a draft of this request by covering all the possible questions and answers in/out of this repository. Then let's come back here.

**Comment by asdofindia** [comment]
Closing this as the task force has been disintegrated.
